### ISSUE TITLE
better to use a Makefile than the Capri build system

### ISSUE THREAD

**Issue by ghost** [flax-lang/flax#1]
Hey 

so i'm not too good at the whole build thing, but I think you should use a makefile instead of the capri thing. it makes it easier for people to compile and use since most *nix systems already have the make command built-in. Just a suggestion though.

Cheers

**Comment by zhiayang** [comment]
Oh hello!

Well capri has binaries for practically every platform. One problem I've faced with makefiles is that they don't support spaces in paths properly, by nature of them being a shell-script extension/derivative.

I don't think not having spaces in file paths is a legitimate limitation, especially since separating words is an integral part of every proto-IE based language (except maybe German hahaha). The Unix world needs to up their game...
