### ISSUE TITLE
Build on linux

### ISSUE THREAD

**Issue by tuguldurio** [flax-lang/flax#29]
How do i actually build the source to try out flax?

**Comment by zhiayang** [comment]
On linux, you just need to install LLVM 7 (see this place for the appropriate sources to add to APT for debian-based distros: https://apt.llvm.org/), `libffi`, and `libmpfr` through your package manager. After that, you should be able to run `make` to compile everything.

**Comment by tuguldurio** [comment]
i have llvm 8 on my system (arch). and when i try `make` i get `llvm-config: command not found
 `

**Comment by chuahou** [comment]
You need llvm 7 to build flax, not llvm 8. I'm not sure if llvm 8 would work since it is a different major version after all.

Once you've installed 7, you may want to check if `llvm-config` has been installed as `llvm-config-7` instead, which would mean you have to export the `LLVM_CONFIG` variable for `make` by running

    $ LLVM_CONFIG=llvm-config-7 make

instead of plain old `make`.

**Comment by zhiayang** [comment]
Ah yes, rolling release distros. I'm also on arch and i accidentally updated llvm to 8.0.0, so i'm kinda in the same situation as you right now. Though my `llvm-config` does show up, so that's a bit strange.

You *could* install llvm-7, but being arch i don't really recommend that, so we're kinda stuck.

i'll keep this issue open until flax gets updated to use llvm 8.

**Comment by zhiayang** [comment]
Commit 0f93013 merged into `develop` moves us from LLVM 7 to LLVM 9, so that should solve builds on rolling-release distros... at least for a few months.
