### ISSUE TITLE
List of currently not implemented features

### ISSUE THREAD

**Issue by ghost** [flax-lang/flax#4]
It would be useful to have a list of what features are not currently implemented. For example, from what I read here => http://flax-lang.github.io/, it seems **Clean Syntax: Expressive and Concise (soon)** is not still implemented.

Thanks!

**Comment by zhiayang** [comment]
Hello!

Yup, I kinda agree that it would be good to have something to work towards.

The current TODO list on the Readme is more for long-term goals and general features rather than something concrete. However, "expressive and concise syntax" isn't exactly a concrete goal either.

I'll get to it soon, thanks!

As a self-reference:
- '++' and '--' operators, both postfix and prefix (easy)
- More overloadable operators (easy)
- Destructors or deinitalisers (should be easy with 'defer' already implemented)
- Generics (wip)
- Type safe variadic functions (both generic-style and Any-type style) (generic style still debatable)
- Better warnings and errors
- Polymorphic types
- Arrays on the heap
- Full type inference (haskell-esque? debatable)
- Proper closures and nested functions (capturing local context)
- Standard Library
